name: Fetch OpenAPI Docs and Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'docs/**'

jobs:
  fetch-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download OpenAPI HTML
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: canonical/snapd-rest-openapi
          name: api-docs
          path: docs/_static/api

  documentation-checks:
    needs: fetch-docs
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: "docs"
      fetch-depth: 0